// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace InAppPurchaseTest
{
	public partial class SettingsViewController : UIView
	{
		public SettingsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
