// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BeerDrinkin.iOS
{
	public partial class CameraViewController : UIViewController
	{
		public CameraViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
