// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BeerDrinkin.iOS
{
	public partial class DescriptionCellHeader : UIView
	{
		public DescriptionCellHeader (IntPtr handle) : base (handle)
		{
		}
	}
}
