// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BeerDrinkin.iOS
{
	public partial class ShakeWelcomeViewController : UIViewController
	{
		public ShakeWelcomeViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
