// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace InAppPurchaseTest
{
	[Register ("SettingsViewController")]
	public partial class SettingsViewController : UIView
	{
		public SettingsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
