// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BeerDrinkin.iOS.Storyboards
{
	public partial class BeerHeaderImageCell : UITableViewCell
	{
		public BeerHeaderImageCell (IntPtr handle) : base (handle)
		{
		}
	}
}
